ruby '>= 2.6.3'

source 'https://rubygems.org'

gem 'activesupport'
gem 'aws-sdk-s3'
gem 'buildkit'
gem 'cocoapods', '~> 1.10.0'
gem 'colorize'
gem 'dogapi'
gem 'faraday'
gem 'fastlane', '2.172'
gem 'fastlane-plugin-appcenter'
gem 'google-api-client'
gem 'google_drive'
gem 'highline'
gem 'htmlentities'
gem 'httplog' # for debugging HTTP requests
gem 'jwt', '~> 2.1.0'
gem 'mustache'
gem 'nokogiri'
gem 'octokit'
gem 'os', '~> 1.0'
gem 'parallel'
gem 'pry' # For debugging Ruby with breakpoints
gem 'pry-rescue'
gem 'pry-stack_explorer'
gem 'rake'
gem 'redcarpet'
gem 'rspec'
gem 'rubocop', '~> 0.93.1'
gem 'ruby-graphviz', '~> 1.2'
gem 'rubyzip'
gem 'slack-notifier'
gem 'slack-ruby-client'
gem 'tty-prompt', '~> 0.18.1'
gem 'tzinfo'
gem 'vcr'
gem 'xcodeproj'
gem 'xcpretty'
gem 'xml-simple'
gem 'plist'

# For Fastlane plugin gems
gem 'fastlane-plugin-store_sizer', '~> 0.2.0'
gem 'fastlane-plugin-bugsnag'
