ruby '>= 2.6.3'

source 'https://rubygems.org' do
  # Gems here
  gem 'activesupport'
  gem 'aws-sdk-s3'
  gem 'buildkit'
  gem 'cocoapods', '~> 1.9.0'
  gem 'colorize'
  gem 'dogapi'
  gem 'faraday'
  gem 'fastlane'
  gem 'fastlane-plugin-appcenter'
  gem 'google_drive'
  gem 'google-api-client'
  gem 'highline'
  gem 'htmlentities'
  gem 'jwt', '~> 2.1.0'
  gem 'mustache'
  gem 'nokogiri'
  gem 'octokit'
  gem 'os', '~> 1.0'
  gem 'parallel'
  gem 'pry'
  gem 'pry-rescue'
  gem 'pry-stack_explorer'
  gem 'rake'
  gem 'redcarpet'
  gem 'rspec'
  gem 'rubocop'
  gem 'ruby-graphviz', '~> 1.2'
  gem 'rubyzip'
  gem 'slack-notifier'
  gem 'slack-ruby-client'
  gem 'tty-prompt', '~> 0.18.1'
  gem 'tzinfo'
  gem 'vcr'
  gem 'xcodeproj'
  gem 'xcpretty'
  gem 'xml-simple'
end
