#!/nix/store/2n8wcj6w27wcd726il271w8j55zdcy0x-ruby-2.7.4/bin/ruby
#
# This file was generated by Nix.
#
# The application 'rake' is installed as part of a gem, and
# this file is here to facilitate running it.
#

ENV["BUNDLE_GEMFILE"] = "/nix/store/jhs1ml1y5m4c2f80hh52nhv3q3ms30ir-gemfile-and-lockfile/Gemfile"
ENV.delete 'BUNDLE_PATH'
ENV['BUNDLE_FROZEN'] = '1'
ENV['BUNDLE_IGNORE_CONFIG'] = '1'

# Bundix paths
# export PATH='/nix/store/l2a2skm51si13z4s5r3ffymq09rss01b-nix-2.3.15/bin'${PATH:+':'}$PATH
# export PATH='/nix/store/c9j26mfcz1d3v904f74wzciyfb72lp1q-nix-prefetch-git/bin'${PATH:+':'}$PATH
# export PATH='/nix/store/b766bai8w3dkl7ii9sykxcaby1cs83bi-bundler-2.2.24/bin'${PATH:+':'}$PATH
# export GEM_HOME='/nix/store/b766bai8w3dkl7ii9sykxcaby1cs83bi-bundler-2.2.24/lib/ruby/gems/2.7.0'
# export GEM_PATH='/nix/store/b766bai8w3dkl7ii9sykxcaby1cs83bi-bundler-2.2.24/lib/ruby/gems/2.7.0'

# Original
# Gem.paths = { 'GEM_HOME' => "/nix/store/v7mwidh25i9vk6hra46rj3lgzlaacym3-rake-12.3.2/lib/ruby/gems/2.7.0" }

# New
Gem.paths = { 'GEM_HOME' => "/nix/store/b766bai8w3dkl7ii9sykxcaby1cs83bi-bundler-2.2.24/lib/ruby/gems/2.7.0" }


$LOAD_PATH.unshift "/nix/store/b766bai8w3dkl7ii9sykxcaby1cs83bi-bundler-2.2.24/lib/ruby/gems/2.7.0/gems/bundler-2.2.24/lib"

require 'bundler'
Bundler.setup()

load Gem.bin_path("rake", "rake")
